[package]
authors = []
edition = "2021"
name = "lingua_nif"
version = "0.2.1"

[lib]
crate-type = ["cdylib"]
name = "lingua_nif"
path = "src/lib.rs"

[dependencies]
lingua = "1.6.2"
rustler = "0.34.0"
